version: '3'

services:
  juqte:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app/

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db-data:/data/db